# Generated by Django 3.1.4 on 2021-01-24 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_plotly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='colorway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_plotly.palette'),
        ),
    ]
