# Generated by Django 3.2.10 on 2022-04-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_plotly', '0002_layout_colorway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='colorway',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Layout',
        ),
        migrations.DeleteModel(
            name='Palette',
        ),
    ]
